name: Create and publish the Standalone LXC image

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'build manually trigger'
        required: true
        default: 'triggered by developer'
      blockchain:
        description: 'Blockchain'
        required: true
        default: 'dymension'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 35840
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set the config files
        run: |
            chmod +x build/set-config-files.sh
            ./build/set-config-files.sh ${{ inputs.blockchain }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Install distrobuilder
        run: |
          go install github.com/lxc/distrobuilder/distrobuilder@latest

      - name: Build LXC image
        run: |
          sudo -E $(go env GOPATH)/bin/distrobuilder build-lxc build/lxc/crynux-node.lxc.yaml -o image.architecture=$(dpkg --print-architecture)

      - name: Change ownership of artifacts
        run: sudo chown runner:runner rootfs.tar.xz lxc.tar.xz

      - name: Upload LXC image artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lxc-image-${{ inputs.blockchain }}
          path: |
            rootfs.tar.xz
            lxc.tar.xz
