name: Create and publish the Standalone LXC image

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'build manually trigger'
        required: true
        default: 'triggered by developer'
      blockchain:
        description: 'Blockchain'
        required: true
        default: 'dymension'
      tag:
        description: 'Git tag to build from (if not specified, use selected branch with git hash)'
        required: false

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      BLOCKCHAIN: ${{ inputs.blockchain || 'dymension' }}

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 35840
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.tag || github.ref }}
          submodules: recursive

      - name: Set the config files
        run: bash build/set-config-files.sh "$BLOCKCHAIN"

      - name: Update LXC YAML with dynamic values
        id: update-yaml
        run: |
          # Get commit hash for version
          SHA_SHORT=$(git rev-parse --short HEAD)

          # Determine version based on tag input
          if [[ -n "${{ inputs.tag }}" ]]; then
            # Use specified tag as version
            VERSION="${{ inputs.tag }}"
          else
            # Use selected branch with git hash
            VERSION="${SHA_SHORT}"
          fi

          echo "Using version: ${VERSION}"
          echo "Using blockchain: ${BLOCKCHAIN}"

          # Export for later steps
          echo "sha_short=${SHA_SHORT}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          # Create a full version that includes blockchain for file naming
          FULL_VERSION="${VERSION}-${BLOCKCHAIN}"
          echo "full_version=${FULL_VERSION}" >> $GITHUB_OUTPUT

          # Replace placeholders in LXC YAML
          sed -i "s/RELEASE_VERSION/${VERSION}/g" build/lxc/crynux-node.lxc.yaml
          sed -i "s/BLOCKCHAIN_NAME/${BLOCKCHAIN}/g" build/lxc/crynux-node.lxc.yaml

          echo "Updated LXC YAML file:"
          cat build/lxc/crynux-node.lxc.yaml

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y debootstrap gpg squashfs-tools

      - name: Install distrobuilder via Snap
        run: |
          # Per official documentation, snap is the recommended way to install distrobuilder.
          # We rely on the snap to be self-contained with its core dependencies.
          sudo snap install distrobuilder --classic

      - name: Build Incus image with distrobuilder
        run: |
          # The snap installation places distrobuilder directly in the PATH.
          # Use build-incus to generate Incus format images
          sudo -E distrobuilder build-incus build/lxc/crynux-node.lxc.yaml -o image.architecture=$(dpkg --print-architecture)

      - name: List generated files
        run: |
          echo "Files generated by distrobuilder:"
          ls -la
          echo "Checking for Incus image format files:"
          find . -name "incus.tar.xz" -o -name "rootfs.squashfs" | head -10

      - name: Rename artifacts with version
        run: |
          FULL_VERSION="${{ steps.update-yaml.outputs.full_version }}"
          sudo mv incus.tar.xz "incus-${FULL_VERSION}.tar.xz"
          sudo mv rootfs.squashfs "rootfs-${FULL_VERSION}.squashfs"
          echo "Renamed files to include full version: ${FULL_VERSION}"
          ls -la incus-*.tar.xz rootfs-*.squashfs

      - name: Change ownership of artifacts
        run: |
          FULL_VERSION="${{ steps.update-yaml.outputs.full_version }}"
          sudo chown runner:runner "incus-${FULL_VERSION}.tar.xz" "rootfs-${FULL_VERSION}.squashfs"

      # Setup SSH agent for secure key management
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.REGISTRY_SSH_KEY }}

      - name: Add server to known hosts
        run: |
          ssh-keyscan -p ${{ secrets.REGISTRY_PORT }} ${{ secrets.REGISTRY_HOST }} >> ~/.ssh/known_hosts

      # Direct scp upload of incus image metadata and rootfs to avoid time-consuming tar & untar
      - name: Upload incus image metadata to registry server
        run: |
          timeout 30m scp -P ${{ secrets.REGISTRY_PORT }} \
            "incus-${{ steps.update-yaml.outputs.full_version }}.tar.xz" \
            ${{ secrets.REGISTRY_USERNAME }}@${{ secrets.REGISTRY_HOST }}:/var/www/lxc/uploads/

      - name: Upload incus image rootfs to registry server
        run: |
          timeout 30m scp -P ${{ secrets.REGISTRY_PORT }} \
            "rootfs-${{ steps.update-yaml.outputs.full_version }}.squashfs" \
            ${{ secrets.REGISTRY_USERNAME }}@${{ secrets.REGISTRY_HOST }}:/var/www/lxc/uploads/

      - name: Process image on server
        uses: appleboy/ssh-action@v1.2.2
        env:
          VERSION: ${{ steps.update-yaml.outputs.full_version }}
        with:
          host: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          key: ${{ secrets.REGISTRY_SSH_KEY }}
          port: ${{ secrets.REGISTRY_PORT }}
          envs: VERSION
          script_path: build/lxc/process-lxc-images.sh
          command_timeout: "30m"

      - name: Upload Incus image artifacts (backup)
        uses: actions/upload-artifact@v4
        with:
          name: crynux-node-incus-image-${{ steps.update-yaml.outputs.full_version }}
          path: |
            incus-${{ steps.update-yaml.outputs.full_version }}.tar.xz
            rootfs-${{ steps.update-yaml.outputs.full_version }}.squashfs
