name: Release the LXC image for a specific blockchain

on:
  workflow_call:
    inputs:
      blockchain:
        required: true
        type: string
      release_version:
        required: true
        type: string

jobs:
  build-the-lxc-image:
    name: Build the release LXC image
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      BLOCKCHAIN: ${{ inputs.blockchain }}

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 35840
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set the config files
        run: bash build/set-config-files.sh "$BLOCKCHAIN"

      - name: Update LXC YAML with dynamic values
        id: update-yaml
        run: |
          VERSION="${{ inputs.release_version }}"
          IMAGE_TAG="${{ inputs.release_version }}"
          echo "Using code version: ${VERSION}"
          echo "Using image tag: ${IMAGE_TAG}"
          echo "Using blockchain: ${BLOCKCHAIN}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          FULL_VERSION="${IMAGE_TAG}-${BLOCKCHAIN}"
          echo "full_version=${FULL_VERSION}" >> $GITHUB_OUTPUT
          sed -i "s/RELEASE_VERSION/${IMAGE_TAG}/g" build/lxc/crynux-node.lxc.yaml
          sed -i "s/BLOCKCHAIN_NAME/${BLOCKCHAIN}/g" build/lxc/crynux-node.lxc.yaml
          cat build/lxc/crynux-node.lxc.yaml

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y debootstrap gpg squashfs-tools

      - name: Install distrobuilder via Snap
        run: |
          sudo snap install distrobuilder --classic

      - name: Build Incus image with distrobuilder
        run: |
          sudo -E distrobuilder build-incus build/lxc/crynux-node.lxc.yaml -o image.architecture=$(dpkg --print-architecture)

      - name: List generated files
        run: |
          ls -la
          find . -name "incus.tar.xz" -o -name "rootfs.squashfs" | head -10

      - name: Rename artifacts with version
        run: |
          FULL_VERSION="${{ steps.update-yaml.outputs.full_version }}"
          sudo mv incus.tar.xz "incus-${FULL_VERSION}.tar.xz"
          sudo mv rootfs.squashfs "rootfs-${FULL_VERSION}.squashfs"
          ls -la incus-*.tar.xz rootfs-*.squashfs

      - name: Change ownership of artifacts
        run: |
          FULL_VERSION="${{ steps.update-yaml.outputs.full_version }}"
          sudo chown runner:runner "incus-${FULL_VERSION}.tar.xz" "rootfs-${FULL_VERSION}.squashfs"

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.REGISTRY_SSH_KEY }}

      - name: Add server to known hosts
        run: |
          ssh-keyscan -p ${{ secrets.REGISTRY_PORT }} ${{ secrets.REGISTRY_HOST }} >> ~/.ssh/known_hosts

      - name: Upload incus image metadata to registry server
        run: |
          timeout 30m scp -P ${{ secrets.REGISTRY_PORT }} \
            "incus-${{ steps.update-yaml.outputs.full_version }}.tar.xz" \
            ${{ secrets.REGISTRY_USERNAME }}@${{ secrets.REGISTRY_HOST }}:/var/www/lxc/uploads/

      - name: Upload incus image rootfs to registry server
        run: |
          timeout 30m scp -P ${{ secrets.REGISTRY_PORT }} \
            "rootfs-${{ steps.update-yaml.outputs.full_version }}.squashfs" \
            ${{ secrets.REGISTRY_USERNAME }}@${{ secrets.REGISTRY_HOST }}:/var/www/lxc/uploads/

      - name: Process image on server
        uses: appleboy/ssh-action@v1.2.2
        env:
          VERSION: ${{ steps.update-yaml.outputs.full_version }}
          LATEST: "true"
          BLOCKCHAIN: ${{ env.BLOCKCHAIN }}
        with:
          host: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          key: ${{ secrets.REGISTRY_SSH_KEY }}
          port: ${{ secrets.REGISTRY_PORT }}
          envs: VERSION,LATEST,BLOCKCHAIN
          script_path: build/lxc/process-lxc-images.sh
          command_timeout: "30m"

      - name: Upload Incus image artifacts (backup)
        uses: actions/upload-artifact@v4
        with:
          name: crynux-node-incus-image-${{ steps.update-yaml.outputs.full_version }}
          path: |
            incus-${{ steps.update-yaml.outputs.full_version }}.tar.xz
            rootfs-${{ steps.update-yaml.outputs.full_version }}.squashfs
